spring:
#  datasource:
###    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=1;MODE=MYSQL;
#    url: jdbc:mysql://13.125.206.146:3306/datum?useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: moa
#    password: moaproject
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
#        database-platform: org.hibernate.dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    hibernate:
      ddl-auto: validate
#    defer-datasource-initialization: true
#    generate-ddl: true
  sql:
    init:
      mode: always

server:
  port: 8080